In [2]:
import numpy as np

In [30]:
simulation_length = 1
steps_per_year = 10
steps = int(steps_per_year * simulation_length)
time_grid = np.linspace(start=0, stop=simulation_length, num=1 + steps)
dt = 1 / steps_per_year
r = np.array([0.5, 0.4, 0.3, 0.4, 0.3, 0.2, 0.3, 0.4, 0.3, 0.4, 0.2])
q = np.array([0.1, 0.1, 0.2, 0.4, 0.2, 0.1, 0.1, 0.1, 0.1, 0.4, 0.1])
drift = r - q

integrated_drift = np.cumsum(drift * dt)

In [31]:
print(drift)
print(integrated_drift)

[0.4 0.3 0.1 0.  0.1 0.1 0.2 0.3 0.2 0.  0.1]
[0.04 0.07 0.08 0.08 0.09 0.1  0.12 0.15 0.17 0.17 0.18]


In [12]:
from scipy.integrate import trapezoid

trapezoid(drift, time_grid)

array([0.155])

In [6]:
integrated_drift

array([0.04, 0.07, 0.08, 0.08, 0.09, 0.1 , 0.12, 0.15, 0.17, 0.17, 0.18])

In [3]:
arr = np.array([0.1, 4, 0.2, 0.3, 4, 0.2])
a = 0.57
np.cumsum(arr * a) - np.cumsum(arr) * a

array([0., 0., 0., 0., 0., 0.])

In [7]:
from Project.notebooks.notebook_utils import foo

foo()

2